version: '3'
services:
  postgres-pokedex:
    image: postgres
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=1234

  pokedex-app:
    image: pokedex-app:1.0
    ports:
      - 8080:8080
    entrypoint: ["./pokedex-app", "postgres://postgres:1234@postgres-pokedex:5432/postgres?sslmode=disable"]
    depends_on:
      - postgres-pokedex
    restart: always
