// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Pokemon struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Abilities   []string `json:"abilities"`
	Type        []string `json:"type"`
}

type PokemonInput struct {
	ID          *string  `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Abilities   []string `json:"abilities"`
	Type        []string `json:"type"`
}
